### ISSUE TITLE
v1.1.1 no longer compiles with rust 1.33

### ISSUE THREAD

**Issue by MightyPork** [Mange/mpris-rs#46]
hey, been using your library and it worked great until the latest rust update that changed `Duration` to use `u128` (which is pretty stupid if you ask me, but,, oh well)

```
error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/mpris-1.1.1/src/player.rs:153:53
    |
153 |         self.set_position_in_microseconds(track_id, position.as_micros())
    |                                                     ^^^^^^^^^^^^^^^^^^^^ expected u64, found u128

```

it should be a one-line fix. could you fix that in 1.1.2? the 2.0.0 rc is still not on crates.io, and everything depending on "^1.1" will break anyway due to this regression

**Comment by Mange** [comment]
Yes, I will fix this. It'll be some time before I got time to sit at my computer and work, tough. If you're up for it a PR would be most welcome.

There's a branch for 1.x I think. You could branch off of there.

**Comment by Mange** [comment]
I think that my fix for it in the master branch could be backported via git cherry-pick. 🍒

**Comment by MightyPork** [comment]
didn't find the fix you mentioned, but a possible fix is in pr #47. had to fix a bunch of other stuff too, to shut up cargo/clippy warnings

**Comment by Mange** [comment]
```
~mpris-rs › git name-rev HEAD
HEAD tags/v1.1.2^0
~mpris-rs » rustup run 1.33.0 cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
```

This is fixed on 1.1.2. Closing this issue.
